name: Build Cosmic Edit Nightly

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Enable long paths in Git
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in Windows
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout Cosmic Edit
        uses: actions/checkout@v4
        with:
          repository: pop-os/cosmic-edit
          ref: master
          path: cosmic-edit

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          target: x86_64-pc-windows-gnu

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "cosmic-edit -> target"

      - name: Build release
        working-directory: cosmic-edit
        run: cargo build --release

      - name: List build directory contents
        working-directory: cosmic-edit/target/release
        shell: powershell
        run: Get-ChildItem -Force

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: cosmic-edit-exe
          path: cosmic-edit/target/release/cosmic-edit.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: cosmic-edit-exe
          path: artifacts

      - name: List artifacts directory contents
        run: ls -la artifacts

      - name: Get the current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create release directories and zip
        run: |
          mkdir -p cosmic-edit-release
          mv artifacts/cosmic-edit.exe cosmic-edit-release/
          zip -r cosmic-edit-windows.zip cosmic-edit-release/*
          
      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
