name: Build Zing Nightly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          repository: sukeesh/zing
          ref: main
          # path: zing

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu

    - name: Install dependencies
      run: sudo apt-get install -y mingw-w64

    - name: Build
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Zip binary
      run: |
        mkdir -p artifacts
        zip artifacts/zing.zip target/x86_64-pc-windows-gnu/release/zing.exe
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: zing
        path: artifacts/zing.zip
