name: Build Zing Nightly

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          repository: sukeesh/zing
          ref: main
          # path: zing

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu

    - name: Install dependencies
      run: sudo apt-get install -y mingw-w64

    - name: Build
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Zip binary
      run: |
        mkdir -p artifacts
        zip artifacts/zing.zip target/x86_64-pc-windows-gnu/release/zing.exe
  
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: zing
        path: artifacts/zing.zip
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get the current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

     # - name: Create release directories and zip
     #   run: |
     #     mkdir -p zing-release
     #     mv artifacts/zing.zip zing-release/
         
      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: |
            zing.zip
